### ISSUE TITLE
Blue bar across main menu screen.

### ISSUE THREAD

**Issue by CitrusHappy** [Windblade-GR01/Ikemen_GO#111]
Using newest artifact of Ikemen GO for windows x64, custom screenpack. Getting this blue bar on the menu and no-where else.
[Imgur Link to Issue](https://i.imgur.com/3aw9idB.png)

**Comment by K4thos** [comment]
the reason for the wrong position is because you set game resolution to 1080p while your screenpack has localcoord set to 720p.

I don't think there is issue with 4:3 resolutions being higher than localcoord. I have no idea how to fix this problem for wide resolutions.
