### ISSUE TITLE
Selection screen bugs / Not yet implemented

### ISSUE THREAD

**Issue by CitrusHappy** [Windblade-GR01/Ikemen_GO#112]
Windows x64 newest Ikemen GO, custom screenpack. 

### PROBLEMS

- Select screen random button not appearing despite its proper sprite index.

- Animated selection cursor (four frames of animation) not appearing properly [SEE BELOW]
[WORKING - Mugen Engine](https://i.imgur.com/qoBXVnr.gif)
[BROKEN - Ikemen GO](https://i.imgur.com/t6RMpFI.png)

**Comment by K4thos** [comment]
please upload that whole screenpack for testing

**Comment by CitrusHappy** [comment]
[testbuild](https://www.mediafire.com/file/l28em3ssf9sovpq/Citrus%27_Ikemen_GO_TESTBUILD.zip/file)

**Comment by K4thos** [comment]
Ikemen is trying to render this animation using sprites stored in data/Select.sff. It looks like mugen uses default sff file (assigned via [Files] section) for all select screen animation other than backgroundefs.

Fixed locally. For now you can make it work by copying problematic sprites from data/system.sff to data/Select.sff.
