### ISSUE TITLE
Linux build doesnt include "external" folder and requesting some debugging tools.

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen_GO#114]
The Linux zip doesn't have the external folder included, crashing to the desktop for obvious reasons, unzipping the windows one in a folder and copying the Linux executable to that folder solves the trouble.

BTW guys, I just deleted my suggestions about improving debug mode because bulky messages on discord are kinda silly IMO.

Debug Mode
So if you can improve the debug mode in Ikemen GO to show these errors as follows.
When a character does call a variable, map or fvar that is not being declared in any part of the character code or common files.
When a character doesn't call a valid ID partner(for the new awesome tag mode)
When a character doesn't call a valid numhelper or explod.
When a character doesn't call a valid stateno.

Displaytoclipboard
Also if you can add some new parameters to the  state type Displaytoclipboard
Juggle: Display current character juggle, pretty cool for debugging combos.
Current or last helper ID: This is kinda tricky but if you think in a way to show what is the current or the last helper being called/used for the char, that would be really useful to debugging helpers.

Debug Triggers
My point about debugging triggers is to set the character to a default state when an error was detected,  so one can avoid the character freezing in the middle of the fight, pretty much what Ctrl + I do but automatically.

Something like this
[State] 
type = changestate
trigger1 = novalidstateno
trigger2 = novalidhelper
trigger2 = time > 50; optional, sometimes helpers doesn't affect the current stateno of the char, the helper just doesn't show up, but the character doesn't freeze, the state ends, set to state 0 again and continue to fight, but there are cases where the character is waiting for the helper to return a value to end the state
value = 0
ctrl = 1 

I know this doesn't happen often with well-coded chars, but let's be realistic, this is Mugen.

CurrentStateno
This is mostly for Simul, Simul is a bug fest because most targetbind states cause the character to behave as not intended if any of the two characters involved in the movement is being hit by another character.
For example, Ryo Sakasaki Zanretsuken movement 646 A or C, Ryo start giving rapid punches to the opponent, if another character hits Ryo, the character Ryo was punching just goes flying up, getting out of the stage.
If the one getting hit is the opponent Ryo was punching, Ryo could freeze because sometimes mugen developers uses  p2stateno or enemynear,stateno as triggers to continue with the state or change the state.

For example
[State] 
type = changestate
trigger1 = currentstateno && time > 100; detects the current stateno and checks if the character has been on the same stateno for more than 100 ticks.
value = 0 
ctrl = 1 
This set the character to state 0 again with full control of itself

[State] 
type = posset; This time I want to set the character to the floor again in the case it got freeze in the air
trigger1 = currentstateno && time > 100
y = 0 ; or maybe the floor variable of the stage.

These are my humble suggestions, thanks in advance. It doesn't matter if you take these suggestions into account or not, I'm really glad you are around here doing cool stuff for the engine.

**Comment by Windblade-GR01** [comment]
Fixed the Linux executable not including the `external` folder.

**Comment by Orochikyocr** [comment]
About currentstateno, because I think I can get the results Im looking for with trigger Stateno.
It was a rush idea from my part.
