### ISSUE TITLE
Combo counter disappears in Tag mode

### ISSUE THREAD

**Issue by pokeshark** [Windblade-GR01/Ikemen_GO#115]
first, thanks for implementing tag out!

found a small issue with combo counter disappearing in tag matches:
https://youtu.be/3EJ_YW4C6ds (recorded with a fresh build with no additions)

@ 00:22 combo counter disappears when hitting incoming character
@ 00:38 combo counter appears briefly during super, then it disappears again for regular combos

hope this helps.

**Comment by K4thos** [comment]
this is already fixed
