### ISSUE TITLE
[Constants] Character Based Override

### ISSUE THREAD

**Issue by SibilantScream** [Windblade-GR01/Ikemen_GO#122]
Some creators use different animation\stateno numbers making common.const unable to account for those.

An override inside the character's files as inside the .def file or inside a predefined .const file inside the character folder for back compatibilty with Mugen.

**Comment by K4thos** [comment]
it already works the way you described it: https://github.com/K4thos/Ikemen_GO/wiki#constants

**Comment by SibilantScream** [comment]
I'm must've tried to declare them inside .def instead, had to read the document.
Thanks, it works fine.
