### ISSUE TITLE
Able to use CNS/ST File for Tag team If I can't learn how ZSS Works?

### ISSUE THREAD

**Issue by cyliamargatroid** [Windblade-GR01/Ikemen_GO#125]
Is it Possible if we also use tag,st as a Customizable tag team stuff?

**Comment by SibilantScream** [comment]
That'd help alot streamlining common statedefs like guardcrush.
Another thing that'd help is the ability to set precedence for negative .zss & .cns states since most command triggers pass through .cmd & trigger a move there before they get to .zss.

**Comment by Windblade-GR01** [comment]
Yes a CNS file it can be used.

**Comment by K4thos** [comment]
path to each file that handles common global code can be changed via CommonStates in config.json. No problem with replacing zss file with cns there (it won't be done by default though since cns has absolutely no advantages over zss)
