### ISSUE TITLE
How do I go back on Gameepad?

### ISSUE THREAD

**Issue by EVILEDLIBRE** [Windblade-GR01/Ikemen_GO#129]
Hello. I am trying to figure out how to go backwards in the menu with the 'gamepad.'

Technically, I'm using a custom built fight stick that's using an encoder that translates inputs through a USB cable that the computer reads as 'x-box 360' gamepad inputs. But, the principle should be the same.

I go into the menu to set inputs for the 'joystick.' All the directions, action keys, and start button for gameplay work perfectly. But, I can not figure out how to go backwards the same way that the escape key does.

This is forcing me to use the keyboard to do this. I am thinking about building an arcade cabinet and really don't want to have to keep a keyboard off to the side just for the singular purpose of hitting the escape key to go back in the menus.

Aslo, what do the "D" and "W" options in the input screen mean? Are these for going backwards? What do they do?

Thank you for your time.

**Comment by K4thos** [comment]
D and W are new buttons. By default used for switching partners in tag mode. But can be assigned as any other mugen button.

There is currently no way to go back using gamepad (it's also not possible in mugen)

**Comment by EVILEDLIBRE** [comment]
It works now. This is great! Thank you! It's much better this way.
