### ISSUE TITLE
Add Mugen 1.1 interpolated animation on screenpacks.

### ISSUE THREAD

**Issue by Windblade-GR01** [Windblade-GR01/Ikemen_GO#13]
Mugen 1.1 add a feature were it can interpolate transparency, position and rotation.
For now Ikemen GO does not implement this feature.

**Comment by NeatUnsou** [comment]
They are already implemented and work with char and stages but not with screenpacks.
This is probably because lua script does not load the AIR Interpolates option.
It will work if lua script can read the Interpolates option.

**Comment by Windblade-GR01** [comment]
I will try to implement it on screenpacks.
Maybe change the title to reflect the changes.
