### ISSUE TITLE
Select.def Grid Portrait Offset & Facing

### ISSUE THREAD

**Issue by SibilantScream** [Windblade-GR01/Ikemen_GO#136]
Some fighting games like KoF 2000 uses non-regular (non-orthogonal?) spacing, purportedly in Mugen you can solve this by using a background portraits & make rows & column in a way you use the lowest distance between 2 portraits which is just too much and add to that you can't use lock\unlock with this method unless there's a way to update the background from a list of all possible permutations, this number of permutations can easily go to unfeasible numbers.

All of this can easily be worked around providing an individual offset for each portrait.

Facing comes in to give the grid left team vs right team feel like in KoF 2000, making editing select.def more flexible than going to fighterfactory & editing sprites themselves.

![Untitled](https://user-images.githubusercontent.com/61993103/82078136-4fe25200-96e9-11ea-825a-5e445fbdc074.png)

**Comment by K4thos** [comment]
done, both features are implemented. Can be used like this under screenpack [Select Info]:
`cell.[col].[row].offset = x, y
cell.[col].[row].facing = -1`

Example:
`
cell.1.1.offset = -2, 4
cell.3.1.offset = -20, -8
cell.2.1.facing = -1
`
![ikemen000](https://user-images.githubusercontent.com/8928195/82099178-ef620d80-9706-11ea-9f15-b5dd9a62a43a.png)
