### ISSUE TITLE
Crosspaltform build for MacOS

### ISSUE THREAD

**Issue by taglme** [Windblade-GR01/Ikemen_GO#140]
Hi! I was looking for a solution for cross-compiling my project and stumbled upon the appveyor log page with the same error as in my project. Log is referenced to this project.
https://ci.appveyor.com/project/Windblade-GR01/ikemen-go
There is the same error as in my build
`# github.com/sqweek/dialog/cocoa
In file included from go/pkg/mod/github.com/sqweek/dialog@v0.0.0-20200304031853-0dcd55bfe06a/cocoa/dlg_darwin.go:6:
./dlg.h:1:10: fatal error: 'objc/NSObjcRuntime.h' file not found
#include <objc/NSObjcRuntime.h>`

Could you tell me how you managed to fix this cross-compilation error for macros? Thanks a lot!

**Comment by Windblade-GR01** [comment]
So it seems that Sqweek fixed crosscompilation.
Does work for you now?
