### ISSUE TITLE
Broken compiled exe 

### ISSUE THREAD

**Issue by 1JAS1** [Windblade-GR01/Ikemen_GO#155]
Whenever I try to compile the source code with the build.bat file I always get this warning : 
```
Building Ikemen GO...

# github.com/timshannon/go-openal/openal
go\pkg\mod\github.com\timshannon\go-openal@v0.0.0-20170220204755-e0ed4c67cffe\openal\alcCore.go:29:16: warning: 'alcGetString' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
   29 | const ALCchar *alcGetString( ALCdevice *device, ALCenum param );
      |                ^~~~~~~~~~~~

Press any key to continue . . . 

```
**It does however produce an executable but its not the right size its 24,634 kb. And obviously it doesn't work**

I've triple checked and I have been using the correct openal version

does anyone have any idea how to fix this its driving me insane

**Comment by slzero-X** [comment]
I have the same problem despite following the exact instructions too.
Maybe there is an error in the code that causes something, when I used x64dbg, I found the cause:
It was a memory access violation, and where in the code is it causing it? I have no idea.

**Comment by slzero-X** [comment]
Thank you for closing this Windblade-GR01, I used to not understand why it didn't work. Now that I have found the cause of the crash, I feel proud of myself.
