### ISSUE TITLE
Some bugs I just run into.

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen_GO#21]
Used last Ikemen GO release by Gacel with a fresh mugen install.

1 - It seems Ikemen Go doesnt like at too many cells on Screenpacks, used a screenpack that have at least one thousands cells and Ikemen GO goes wild, eating all my ram up to even, freezing windows. Change the screenpack system.def file and reduce the quantity of cells to 200 and now it load normally. 

2 - Chars caused Ikemen Go to crash to desktop because function Game() on select.lua cant process the line  "trigger1 = command != "hold_a". Chars works fine on Mugen 1.1 and also they work on Ikemen GO on Watch mode.

3- I did manage to set the screenpack Im using to the right localcoord, everything looks fine, but  Option Screen and Loading screen looks so tiny. Changed localcoord parameters on both localcoord.lua, motif.lua and system.def

4- Menu has a weird behavior, I did remove the Network option from main menu, it works fine if you use the down key, when it reaches the last menu item, one more down key press sends the cursor to the first item. But if I put the cursor on the first menu item and press UP it goes to a non visible option, once in, it is the network option.  

[ikemenerror.txt](https://github.com/Windblade-GR01/Ikemen_GO/files/3186277/ikemenerror.txt)
Here is a log file of the error.

**Comment by Windblade-GR01** [comment]
1. I'll check the reason for the ram usage, could you send the screenpack that you are using?

2.  Could you send a example of the char, I'll check the reason of the crash.

**Comment by Windblade-GR01** [comment]
1. I'll check the reason for the ram usage, could you send the screenpack that you are using?
(Is probably related to the char icon loading)

2.  Could you send a example of the char, I'll check the reason of the crash.

3. The option menu is not scaled for now I'm searching a way to make it scale with the localccord but K4thos code is hard to navigate, but don't worry I'm working on it.

4. That is new! But it would not be too hard to fix.

Thanks for reporting the bugs!

**Comment by Orochikyocr** [comment]
2 - Chars caused Ikemen Go to crash to desktop because function Game() on select.lua cant process the line "trigger1 = command != "hold_a". Chars works fine on Mugen 1.1 and also they work on Ikemen GO on Watch mode.

Took the translator to check what those Japanese words meant, it says it cant find the command "hold_a".
The characters Im using are part of a full game and they use a common command.cmd file located in the data folder. When I checked the def file, I saw this:
cmd =..\..\data\command.cmd ,  
changed to : cmd =data\command.cmd, didnt work, 
then changed again to: 
cmd  =..\data\command.cmd It worked!! Chars are working now.

Sadly Fighter Factory and Mugen 1.1 doesnt like how IkemenGO arrange the folder search and this change breaks fighter factory loading the common files used by these chars. Nothing to be mad about, just pointing out this.

Stages works very well on versus, practice and watch but for some reason they trigger an error when trying to play Team Arcade. 
Error
.\script\select.lua:111: attempt to index a non-table object(nil)
stack traceback:
	.\script\select.lua:111: in function 'f_setZoom'
	.\script\select.lua:939: in function 'f_selectAdvance'
	script/main.lua:1587: in function 'f_mainMenu'
	script/main.lua:2168: in main chunk
	[G]: ?

Gonna delete all the zoom functions inside stage.def files to see if the error is triggered by that.

Ill be able to upload the full game converted to IkemenGO soon, I´ll be putting the original system.def and select.def files in a folder, so you can use them instead of my files and see the ram eating by yourself.

Thanks for answering.

**Comment by Windblade-GR01** [comment]
About he upper directory thing.
That's the way windows parses directories could you try it yourself.
Open CMD and type ``cd ...`` and see that nothing happens.
Also type ``cd ..`` and it will go to the upper directory.
I'll search a way to make ``...`` work.
Also I'll check the intro directory thing.

The problem with team arcade is in the lua files (K4thos code again)
I'll check the error.

The ram eating is probably allocating ram for empty spaces...

**Comment by Orochikyocr** [comment]
Damn, Im really sorry. This is the line as it comes originally on the chars.
..\..\data\command.cmd 
I dont know how  I missed that "\".

**Comment by Orochikyocr** [comment]
Bro can you check out this video.
https://youtu.be/Yaa90qm1nbM
It seems Ikemen doesnt use the velocity values as Mugen does.
