### ISSUE TITLE
Stages look bigger than Characters

### ISSUE THREAD

**Issue by Mark85Mete** [Windblade-GR01/Ikemen_GO#22]
[(https://cdn.discordapp.com/attachments/268327206055444481/579022973931880458/Ikemen_GO_2019-05-17_22-09-28.png)]
[(https://cdn.discordapp.com/attachments/268327206055444481/579039734177726543/mugen002.png)]

**Comment by Windblade-GR01** [comment]
Interesting maybe is related how stagefit works on Mugen.
Could you specify what stage are you using?

**Comment by Orochikyocr** [comment]
Have you tried the zoom options in Video options? it worked for me to make characters to look bigger on the stage.

**Comment by Windblade-GR01** [comment]
Neatonsou is actually working on fixing this.
This was caused because of the localcoord calculations of the char was different from  the stage.

**Comment by Windblade-GR01** [comment]
So the new character scale is implemented.
It should fix this.
