### ISSUE TITLE
Add arcade order to stages.

### ISSUE THREAD

**Issue by Windblade-GR01** [Windblade-GR01/Ikemen_GO#23]
For example, in the [ExtraStages] section.
stages/Boss.def, order=3

Suggested by RagingRowen:
http://mugenguild.com/forum/msg.2441362

**Comment by K4thos** [comment]
I've implemented this feature in this commit: https://github.com/K4thos/Ikemen-GO-Plus/commit/662d08549602c6ecdf1b156be0c2055d3bec8805
Quote from select.def:
 ; - order
 ;   IKEMEN feature: Set the paramvalue to the ordering priority to give the
 ;   stage in arcade modes. If there is at least 1 stage with assigned order,
 ;   the random stages selection for characters of the same order value will be
 ;   limited only to these ordered stages pool.
