### ISSUE TITLE
Mac i'snt building

### ISSUE THREAD

**Issue by eduardocezarinossp** [Windblade-GR01/Ikemen_GO#28]
I`ve done all steps:
```
brew install caskroom/cask/brew-cask
brew install git go
brew install openal-soft
git clone https://github.com/Windblade-GR01/Ikemen_GO
cd Ikemen_GO
./get.sh
./build.sh
```
, but when I run:
./Ikemen_GO.command: line 7: ./Ikemen_GO_mac: No such file or directory

<img width="1440" alt="Captura de Tela 2019-05-31 às 08 06 47" src="https://user-images.githubusercontent.com/24570733/58702044-15b65e00-837b-11e9-8ec5-e92261e851f7.png">

**Comment by Windblade-GR01** [comment]
So I changed the build script directory.
It seems that I forgot to update the mac steps, my fault.

The steps are: 

```
brew install caskroom/cask/brew-cask
brew install git go
brew install openal-soft
git clone https://github.com/Windblade-GR01/Ikemen_GO
cd Ikemen_GO
cd build
./get.sh
./build.sh
```

Once you finish you should have got a new file called Ikemen_GO_mac inside the Ikemen_GO folder.

To run the engine you need a Mugen compatible screen pack.
You can use this one:
https://drive.google.com/uc?export=download&id=16p6rx_WXyJdqAHU3KPaArYc62lo4FJna
Extract it in the Ikemen_GO folder.

**Comment by Windblade-GR01** [comment]
So I changed the build script directory.
It seems that I forgot to update the mac steps, my fault.

The steps are: 

```
brew install caskroom/cask/brew-cask
brew install git go
brew install openal-soft
git clone https://github.com/Windblade-GR01/Ikemen_GO
cd Ikemen_GO
cd build
./get.sh
./build.sh
```

Once you finish you should have got a new file called Ikemen_GO_mac inside the Ikemen_GO folder.

To run the engine you need a Mugen compatible screen pack.
You can use this one:
https://drive.google.com/uc?export=download&id=16p6rx_WXyJdqAHU3KPaArYc62lo4FJna
Extract it in the Ikemen_GO folder.

EDIT:
Seeing the build folder it seems that is the old build version...
And it did build well!
Try renaming the Ikemen_GO file to Ikemen_GO_mac.

**Comment by eduardocezarinossp** [comment]
It works, thanks...! But the screen isn`t getting full, u know how can i do it full screen size?

**Comment by Windblade-GR01** [comment]
You need to set the resolution to your desktop one.
