### ISSUE TITLE
Cornerpush does not work as expected.

### ISSUE THREAD

**Issue by Windblade-GR01** [Windblade-GR01/Ikemen_GO#3]
Crouch block at the end of a stage is pushing back characters who are attacking the defending character in latest Ikemen, in mugen 1.1 they aren't being pushed back though.

Reported by Junkerde
http://mugenguild.com/forum/msg.2434120

Videos:
https://streamable.com/s/5t87b/hgyfjo

Characters used in the video:
https://www.mediafire.com/file/nrhdu6ubu5741dn/characters.zip/file

**Comment by Windblade-GR01** [comment]
It seems that this is not a standard behaviour on MUGEN we need more info on how these characters disable cornerpush.

**Comment by NeatUnsou** [comment]
I think this has already been fixed.
In MUGEN, Cornerpush was disabled by changing the Width.
