### ISSUE TITLE
Restart for Debug Keys Needed But Not Prompted

### ISSUE THREAD

**Issue by EVILEDLIBRE** [Windblade-GR01/Ikemen_GO#30]
When turning debug keys on and off from options, a restart of the engine is required. However, unlike most settings like this, the usual prompt does not appear.

Small bug and easy to work around. But, this could be confusing to new people as the prompt does not warn them.

Discovered this bug when trying to turn off debug keys. X-Arcade Tank Stick presumes MAME format and enters commands in as keyboard keys. Strong punch for Player 1 kept resetting health and timer because default strong punch button (once mapped sensibly) presumes the same keyboard key as this debug key function. Turning off debug keys resolved issue. However, no warning prompt for a restart happened and change did not take effect until restart.

Saving and exiting, after debug keys are turned on or off, should bring up the usual prompt that forces engine shut down.

**Comment by Windblade-GR01** [comment]
Thanks for informing it.
I will fix it asp.

**Comment by Windblade-GR01** [comment]
Fixed with commit https://github.com/Windblade-GR01/Ikemen_GO/commit/90c09f86155e98804249b84424fca9ee552b9c2b
