### ISSUE TITLE
add004 no longer functional?

### ISSUE THREAD

**Issue by Spynathan** [Windblade-GR01/Ikemen_GO#36]
I used to be able to patch add004 in no problem, but after the last update or two it crashes when I try to patch in add004. Not sure if it's an easy fix or not, but it's a pretty decent loss imo at least to lose add004.

**Comment by Windblade-GR01** [comment]
It seems that add004 got updated
http://mugenguild.com/forum/topics/add004basic-160242.0.html

Previously it would need to enable "legacy tag mode" in options but now it works out of the box without the need of patching.

I tested it and it did work on my end by just extracting the files in the data folder.

**Comment by Spynathan** [comment]
Well all I had to do was update... Sorry about that, I'll just close this now.
