### ISSUE TITLE
True Type fonts does not display on lifebars

### ISSUE THREAD

**Issue by Windblade-GR01** [Windblade-GR01/Ikemen_GO#4]
Although TTF loading is implemented there is no code for drawing them.
This only refers to lifebar scenario.
On screenpacks this works correctly.

**Comment by nckgriva** [comment]
Because screenpacks render fonts using TextSprites which have code for drawing ttf. Lifebars call Layout.DrawText. It's an easy fix, you just have to slightly modify _common.go_ and _font.go_
