### ISSUE TITLE
Victory Portrait cannot scale by X

### ISSUE THREAD

**Issue by cyliamargatroid** [Windblade-GR01/Ikemen_GO#43]
I was doing an IKEMEN Project, but then I found a problem with a Victory Portrait.
p1.scale = 1,1 - Default
p1.scale = 2,2 - Could not scale X, but scales Y

**Comment by Orochikyocr** [comment]
Windblade´s computer is on repairs right now. That is why he isnt around here lately. You can post any bug you find here too.
http://mugenguild.com/forum/topics/ikemen-go-bug-reports-and-know-bugs-187803.0.html

**Comment by Windblade-GR01** [comment]
OK, I'm back.
Not on the same computer but back.

I'll check it, the problem seems on the lua side.

**Comment by cyliamargatroid** [comment]
Thank you so much for Fixing Victory Portrait!
