### ISSUE TITLE
After Losing Arcade Mode, The Game closes dIrectly instead of showing the continue screen.

### ISSUE THREAD

**Issue by cyliamargatroid** [Windblade-GR01/Ikemen_GO#44]
Is there any way you can fix this problem, I really apperciate it.

**Comment by Orochikyocr** [comment]
What the Ikemen.txt says?

**Comment by cyliamargatroid** [comment]
./script/select.lua:2518: attempt to index a non-table object(nil)
stack traceback:
	./script/select.lua:2518: in function 'f_continue'
	./script/select.lua:881: in function 'f_selectAdvance'
	script/main.lua:1606: in function 'f_mainMenu'
	script/main.lua:2201: in main chunk
	[G]: ?

**Comment by Orochikyocr** [comment]
You should check if you have the continue.sff and the continue.snd files on data folder. Then you should put the original motif.lua on the script folder after you backup yours. Maybe that could help, it seems Ikemen Go cant find files or settings related to the continue screen.

**Comment by Windblade-GR01** [comment]
Even with the files it still crashes it seems that this is a bug.
I'll search when it broke and revert the changes.

**Comment by cyliamargatroid** [comment]
Not a Problem.

**Comment by Windblade-GR01** [comment]
OK, Fixed.
The bug was introduced by 90c27b0e556e486183fa4b5d00bb0634a387506a
An fixed at 829810225c5b4ba2aef1307c75a3ce2f0eb15552
