### ISSUE TITLE
[Feature] Character Transformations

### ISSUE THREAD

**Issue by cyliamargatroid** [Windblade-GR01/Ikemen_GO#46]
My new Idea was if Goku can transform into SSJ2.
for my ideas:
```
[Forms]
form1 = GokuZ2.def
form2 = SSJ_GokuZ2.def

**Comment by cyliamargatroid** [comment]
Or maybe this...
```
Defination
[form1.info]
sprite=ssjgoku.sff
anim=ssjgoku.air

Statetype
[state 000, sample]
type = Transform
trigger1 = time = 10
form = 1; When set to zero, reforms back to base form.

**Comment by Mike77154** [comment]
This is already possible on state cns, but With a  Def file it Will be superior power

**Comment by K4thos** [comment]
this request (support for real transformation, lifting mugen limitations) is fulfilled by following features, although in different manner than suggested:
- https://github.com/K4thos/Ikemen_GO/wiki#sctrlnew_remapsprite
- https://github.com/K4thos/Ikemen_GO/wiki#char_cns_remappreset
