### ISSUE TITLE
Optional Improvements.

### ISSUE THREAD

**Issue by cyliamargatroid** [Windblade-GR01/Ikemen_GO#55]
code example:
```
stage.portrait.spr = 9000,0
```
shows the Image of a Stage in Select Sceen

**Comment by cyliamargatroid** [comment]
and for Excluding the characters in Survival mode,
```
char, excludesurvival = 1;(A Character gets excluded in Survival Mode.)

**Comment by cyliamargatroid** [comment]
for Linux Version, Make it use the Icon Defined.
For example, If existed in 
```
~/local/share/icons/hicolor/scalable/ikemen.svg
```
Uses this Icon.

**Comment by Windblade-GR01** [comment]
So about the icon, now Ikemen GO can load images as icon .
Also there is a setting that specifies what image to loads as Icon relative to the Ikemen GO folder.
Done this way for allow fullgames his own custom icon and for cross-platform reasons.
