### ISSUE TITLE
[Feature] Select Timer

### ISSUE THREAD

**Issue by Amidweiz** [Windblade-GR01/Ikemen_GO#62]
This one is pretty self explanatory, plenty of fighting games have this in which it gives a time limit upon how long a person can be on the select screen for. I think this would be best implemented under [Select Info] if not it's own subsection

> [Select Timer]
> enabled = 1
> framespercount = 60
> time = 99
> ;Time for when the timer is visible based off of time value, -1 means it's visible all the time
> visibleAt = 10 
> timerFont = 1,0,0
> ;forces the person to have a character when they haven't selected, values are random, currentPos, or any definable character in the select.def file. Default value is random
> forceCharacterSingles = random  
> forceCharacterSimul = currentPos, random
> forceCharacterTurns = kfm, currentPos, random, random

**Comment by K4thos** [comment]
done. Works pretty much as requested but without above mentioned “forceCharacter” customization. The first character is always taken from currently highlighted slot, further team members are randomized.
