### ISSUE TITLE
Failure to read font definition files

### ISSUE THREAD

**Issue by Spynathan** [Windblade-GR01/Ikemen_GO#63]
There seems to be several problems when ikemen go reads definition files for fonts, I've noticed this not only myself but with other screenpacks as well. Examples, Mugen 2077, mega mix remix HD, mugen tournament HD and I'm sure others.

**Comment by cyliamargatroid** [comment]
Probably DEF files that uses TTF or OTF files.

**Comment by Spynathan** [comment]
> Probably DEF files that uses TTF or OTF files.

I did test the fonts by themselves, and they do work and load normally. It's simply the DEF itself that isn't being read properly, they were TTF though. But if the engine loads TTF fine by itself, is that really an issue when it comes to DEF files?

**Comment by Windblade-GR01** [comment]
Spynathan, can you provide the fonts that do not load on your end?

**Comment by Spynathan** [comment]
[fontsMTHD.zip](https://github.com/Windblade-GR01/Ikemen_GO/files/3801039/fontsMTHD.zip)
[fonts2077.zip](https://github.com/Windblade-GR01/Ikemen_GO/files/3801040/fonts2077.zip)
Here's the fonts from mugen tournament HD and mugen 2077, MTHD is one of the most popular imo so I linked it. And mugen 2077 is what I was messing with, so I linked that. That's just the fonts but if you want links to the whole screenpacks (in case the problem is deeper than just the .def) just let me know.

**Comment by Spynathan** [comment]
Works fine in the latest builds for me at least, gonna go ahead and close this.
