### ISSUE TITLE
Randomselect Needs to avoid Characters with Exclude = 1 parameter on it

### ISSUE THREAD

**Issue by cyliamargatroid** [Windblade-GR01/Ikemen_GO#64]
While the randomselect is being hovered, The characters or bonus games were being selected with the exclude=1 Parameter on, is there a way to make randomselect avoid selecting character with exclude=1 Parameter?

**Comment by Windblade-GR01** [comment]
Yeah. That is not supposed to happen I'll fix it.

**Comment by Windblade-GR01** [comment]
Fixed with 4ff10241a8050ae75cf7964c0da2012cd44d6e11
