### ISSUE TITLE
Issue with dependencies 

### ISSUE THREAD

**Issue by FainTMako** [Windblade-GR01/Ikemen_GO#67]
It looks like this is breaking the builder?

# github.com/mewkiz/flac
go/src/github.com/mewkiz/flac/encode.go:55:28: cannot use bw (type *bitio.Writer) as type bitio.Writer in argument to encodeStreamInfo
go/src/github.com/mewkiz/flac/encode.go:59:24: cannot use bw (type *bitio.Writer) as type bitio.Writer in argument to encodeBlock
go/src/github.com/mewkiz/flac/encode.go:98:29: cannot use bw (type *bitio.Writer) as type bitio.Writer in argument to encodeStreamInfo
go/src/github.com/mewkiz/flac/encode_frame.go:69:27: cannot use bw (type *bitio.Writer) as type bitio.Writer in argument to encodeSubframe
go/src/github.com/mewkiz/flac/encode_frame.go:120:57: cannot use bw (type *bitio.Writer) as type bitio.Writer in argument to encodeFrameHeaderBlockSize
go/src/github.com/mewkiz/flac/encode_frame.go:126:81: cannot use bw (type *bitio.Writer) as type bitio.Writer in argument to encodeFrameHeaderSampleRate
go/src/github.com/mewkiz/flac/encode_frame.go:132:37: cannot use bw (type *bitio.Writer) as type bitio.Writer in argument to encodeFrameHeaderChannels
go/src/github.com/mewkiz/flac/encode_frame.go:137:42: cannot use bw (type *bitio.Writer) as type bitio.Writer in argument to encodeFrameHeaderBitsPerSample
go/src/github.com/mewkiz/flac/encode_meta.go:154:25: cannot use bw (type bitio.Writer) as type io.Writer in argument to binary.Write:
	bitio.Writer does not implement io.Writer (Write method has pointer receiver)
go/src/github.com/mewkiz/flac/encode_meta.go:183:24: cannot use bw (type bitio.Writer) as type io.Writer in argument to binary.Write:
	bitio.Writer does not implement io.Writer (Write method has pointer receiver)
go/src/github.com/mewkiz/flac/encode_meta.go:183:24: too many errors

**Comment by Windblade-GR01** [comment]
Yeah I noticed that.
go/src/github.com/mewkiz/flac broke.

For now a the best option is to remove FLAC support until that's fixed.
It was giving problems before but now it affects it actively.

**Comment by FainTMako** [comment]
Great work, that did fix it for me. Forgive my newbness. What is the flac player for? Is that just for music or also for sound effects?

**Comment by Windblade-GR01** [comment]
FLAC is a music format.
https://es.wikipedia.org/wiki/FLAC

It just music.
MP3, WAV ang OGG still work.
