### ISSUE TITLE
Some lifebars/screenpacks crash Ikemen GO

### ISSUE THREAD

**Issue by nckgriva** [Windblade-GR01/Ikemen_GO#7]
Ikemen crashes with [foobar](https://mugenarchive.com/forums/downloads.php?do=file&id=37735-foobar-lifebars-zion) lifebars.

**Comment by Windblade-GR01** [comment]
On my end they worked correctly.
Could you post the error log?

**Comment by nckgriva** [comment]
I have tested them again and now they are working without problems. Seems like one of your patches helped with this issue.

**Comment by Windblade-GR01** [comment]
Nice! seems that we can close the bug.
