### ISSUE TITLE
Too Many Error.

### ISSUE THREAD

**Issue by keito940** [Windblade-GR01/Ikemen_GO#71]
# github.com/timshannon/go-openal/openal
go\src\github.com\timshannon\go-openal\openal\alcCore.go:29:16: warning: 'alcGetString' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
   29 | const ALCchar *alcGetString( ALCdevice *device, ALCenum param );
      |                ^~~~~~~~~~~~
# github.com/timshannon/go-openal/openal
go\src\github.com\timshannon\go-openal\openal\alcCore.go:86:144: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcGetError
go\src\github.com\timshannon\go-openal\openal\alcCore.go:125:95: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCloseDevice
go\src\github.com\timshannon\go-openal\openal\alcCore.go:131:102: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCreateContext
go\src\github.com\timshannon\go-openal\openal\alcCore.go:137:110: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_walcGetIntegerv
go\src\github.com\timshannon\go-openal\openal\alcCore.go:142:151: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_walcGetInteger
go\src\github.com\timshannon\go-openal\openal\alcCore.go:163:109: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureCloseDevice
go\src\github.com\timshannon\go-openal\openal\alcCore.go:171:83: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureStart
go\src\github.com\timshannon\go-openal\openal\alcCore.go:175:81: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureStop
go\src\github.com\timshannon\go-openal\openal\alcCore.go:179:179: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureSamples
go\src\github.com\timshannon\go-openal\openal\alcCore.go:183:179: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureSamples
go\src\github.com\timshannon\go-openal\openal\alcCore.go:183:179: too many errors

**Comment by FainTMako** [comment]
I'm not getting this issue. Make sure that you are following the build instructions line for line.

**Comment by keito940** [comment]
I read it carefully, but the explanation is inappropriate, and `` build_win_alt.md`` doesn't have many explanations such as typographical errors.

**Comment by keito940** [comment]
No Problem. Sorry.

**Comment by pokeshark** [comment]
I am getting the same error. How was this resolved?

I followed the instructions to the letter.

**Comment by Windblade-GR01** [comment]
Can you post your log?

**Comment by pokeshark** [comment]
sorry, my mistake. I backtracked my actions and it turns out I downloaded latest OpenAl version (1.20.1) from page: http://kcat.strangesoft.net/openal.html which is incomptabile.

I downloaded 1.19.1 and compiling went fine.
