### ISSUE TITLE
[Feature] Simul/Tag/Team portraits positioning

### ISSUE THREAD

**Issue by FTSGIGP** [Windblade-GR01/Ikemen_GO#72]
Allow the possibility to manually determine second/third/etc character's portrait coordinates (Simul/Tag/Team) instead of just being able to equally space them with "p1.face.spacing" so they can be asymmetrically placed.

```
p1.c1.face.offset = X,Y
p1.c2.face.offset = X,Y
p1.c3.face.offset = X,Y
...

p2.c1.face.offset = X,Y
p2.c2.face.offset = X,Y
p2.c3.face.offset = X,Y
...
```

My most sincere apologies if this has already been implemented or discussed, haven't found anything about it.

**Comment by K4thos** [comment]
implemented. You can also specify individual scale factor for each member, so you can for example achieve something like this: https://i.imgur.com/qYYSsZ6.jpg
Supported for select, versus and victory portraits. Max amount of portraits to render is set by '_num' parameters (1 portrait by default, like in mugen).
