### ISSUE TITLE
Suggestion, Please Add Mapadd and parentmapadd. 

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen_GO#75]
So far so good with Mapset, I can easily set up variables with mapset and use map to call those mapsets.
Mapset could be easily a much better option than var() if one could change the value of that map with something like "varadd" and "parentvaradd". It would be awesome to change the integer value of a Map() dynamically as you do with normal var().

Thanks for reading this and I hope you could take this suggestion into account.

Edit: parentmapset, will be also really helpful :P

**Comment by Windblade-GR01** [comment]
Done with commit c6003090f571975f1be1b9df648a372bafa66240 and 0754132b908eb354cf830da73123750a3ff29a78
