### ISSUE TITLE
Non-reversing commands

### ISSUE THREAD

**Issue by Amidweiz** [Windblade-GR01/Ikemen_GO#76]
This relates to the buffering system that mugen normally comes with where it will reverse inputs right away when the opponent jumps over them, causing inputs to be harder than usual (especially with cross over combos). It is more explained in this thread http://mugenguild.com/forum/topics/fix-all-your-command-issues-explodsive-buffering-system-180772.0.html but it would be nice if ikemen go plus had this by default.

**Comment by FainTMako** [comment]
This appears to be a restructuring of the character files not really an ikemen thing? I dont see how this could be done by default without a lot of un needed work. Am I understanding this properly?

From the forum post: 

> Adding this system will primarily involve editing your character's .cmd file, but you must also add a few things to their -2 State. It is very important that things be placed in the correct place, or else they won't work!

Im not quite sure this belongs to ikemen unless they specifically felt like undertaking this. It would not be a simple modification from what I can tell.

**Comment by Amidweiz** [comment]
What I meant by this was involving this section specifically rather than implementing said system.

> However, unlike MUGEN, we won't be using "forward" and "back"; the explod system is based entirely on absolute, not relative, directional inputs. That means left and right, instead of forward or back. This is to avoid problems in situations where **the characters are switching sides, and their commands reverse.** By defining everything in terms of left and right, we can ensure that a player can always perform the move they want to perform, and not have engine limitations get in the way. To get a better idea of why this is needed, take a look at this 
![Commands_reversing](http://network.mugenguild.com/jmorphman/images/EXPLODsiveBuffering/Commands_reversing.gif)
Even though Ryu's player starts off by inputting "down", and then "down-forward" (you can also think of this as a "down-right" input), soon after entering "down-forward", Ryu and Chun-Li switch sides. Then, Ryu's player inputs "back" (or rather, a "right" input) and hits light kick, and Ryu still performs Tatsumaki Senpukyaku. If we were using a system that used relative (forward/back) directions only, Ryu's input would look like "down, down-forward, back + LK", and he certainly wouldn't perform his Tatsu given that input!

and having ikemen do this by default rather than needing said system to do it.

**Comment by Windblade-GR01** [comment]
I think commands have some kind of reversion but I'm not sure.
I'll check it.

**Comment by Windblade-GR01** [comment]
So it seems that Ikemen GO for a long time had non-reversing commands added by Suehiro.
We can close this.
