### ISSUE TITLE
Crash to desktop after finishing Arcade mode. 

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen_GO#79]
Symptom: The game closes directly to the desktop after finishing arcade mode.
Version: 0.77.

Log:
./script/storyboard.lua:160: attempt to index a non-table object(nil)
stack traceback:
	./script/storyboard.lua:160: in function 'f_parse'
	./script/storyboard.lua:572: in function 'f_storyboard'
	./script/select.lua:865: in function 'f_selectAdvance'
	script/main.lua:1649: in function 'f_mainMenu'
	script/main.lua:2245: in main chunk
	[G]: ?

What I tried: I did remove from the system.def and the chars all the references to any storyboard.def file 

intro.storyboard =
ending.storyboard=

Still, the game crashes.

Thanks in advance.

**Comment by Windblade-GR01** [comment]
OK.
I'll check it.

**Comment by K4thos** [comment]
can't reproduce this one. Please post a link to character that you've used in arcade mode.

**Comment by Orochikyocr** [comment]
> can't reproduce this one. Please post a link to the character that you've used in arcade mode.

This is still happening with any character. It is a full Game.
Just tested with  0.81 version.
You can download it here, it weights less than 500MB.

https://mega.nz/?fbclid=IwAR3uBtCwhltDwA44JV43aHtF88I3FS7C-RPrhfs9SLlQDkCoLkYjuteTC0g#!MAs2xAzK!ZGOnh33w9Kj3SBQMqtIVwOQ7QqHl_1a70FOFLjQe6NM
