### ISSUE TITLE
Force Closed Ikemen GO Bug report 

### ISSUE THREAD

**Issue by OldGamers** [Windblade-GR01/Ikemen_GO#85]
I cant explain it into text so here a you tube video to show the Force Closed Ikemen GO Bug
https://www.youtube.com/watch?v=Ys2sQb-Ue-A

**Comment by K4thos** [comment]
fixed: https://github.com/K4thos/Ikemen-GO-Plus/commit/365c45ae5345df941d779be0809db79542af1fb1
