### ISSUE TITLE
[Feature] Vars and FVars that go beyond 60 and 40 respectively 

### ISSUE THREAD

**Issue by Amidweiz** [Windblade-GR01/Ikemen_GO#86]
Much like the title implies, It would be neat if Ikemen GO plus weren't arbitrarily (unless if there's an actual reason why they're limited to said amount) limited to 60 Vars (0-59) and 40 Float Vars (0-39). Since there are some characters (warusaki3's CvS characters come to mind) that do get close to the 60 variable limit that mugen has.

**Comment by Windblade-GR01** [comment]
MAP has the same function of unlimited number of VARs (Plus they are named)

**Comment by Windblade-GR01** [comment]
Closing this because has gone stale.
