### ISSUE TITLE
Please make Ikemen Go to ignore "pressed buttons"

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen_GO#90]
I'm on Linux Lubuntu 19.014, the deal is that Linux insists on detecting my two sticks, one Xbox 360 and the other one is a PS3, as triggers being always pressed, despite they are simple buttons.

So in Ikemen Go 0.85 when I try to config any of the sticks, they arent being detected on the Joystick section, but in the Keyboard section, if I press f1 or f2, here the game detect instantly the "pressed button" and set all the buttons to "-11"
This video will help me to elaborate, what happens here when I go to joystick, I am pressing buttons but nothing happens, when I go to keyboard, the "pressed button" just causes havoc. If I press a button that is not a trigger or an Axis the keyboard config detects the button I pressed.

https://streamable.com/gwm0i

**Comment by K4thos** [comment]
this is already fixed
