### ISSUE TITLE
Music is not playing on Arcade mode and Kumite mode

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen_GO#92]
Stage music plays fine on training, VS and watch mode. But doesn't play at all on Arcade and Kumite mode.

Tested with the full game.
https://streamable.com/jf3yb

Tested with another screenpack.
https://streamable.com/s8uwn

**Comment by K4thos** [comment]
I can't reproduce it. Please upload minimal version for testing (preferably with just 1 character, stage and music, everything ready to run).

**Comment by Orochikyocr** [comment]
Tested with  0.88 using default Ikemen screenpack and Kung Fu Man. Stage music working as intended. Sorry for the inconvenience
