### ISSUE TITLE
GNU + Linux OS Version No Longer Working

### ISSUE THREAD

**Issue by EVILEDLIBRE** [Windblade-GR01/Ikemen_GO#93]
This is a fairly recent problem as Verison 0.84 runs fine and is what I am currently using to play IKEMEN GO. I simply downloaded the "Linux" version from the artifacts tab, made the bin able to ran as a program in permissions, and run the engine.

However, when I try this exact same method with the most current version, it tries to run and then crashes instantly.

When I try to run it in from Gnome Terminal, I get the fallowing.

~/Downloads/Ikemen_GO_Linux$ ./Ikemen_GO_linux 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x714ed3]

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetIcon(0xc0000b6fc0, 0xc0002933d0, 0x1, 0x1)
	/code/go/src/github.com/go-gl/glfw/v3.3/glfw/window.go:416 +0xe3
main.(*System).init(0x169dbc0, 0x1e000000280, 0xc0000b26c8)
	/code/src/system.go:410 +0x6b0
main.main()
	/code/src/main.go:306 +0x1619

I am running a 64-Bit Trisquel 9.0 Beta GNU + Linux Operating System. If it helps to understand what this is, it's a fork of ubuntu that strips out everything proprietary. So, no Non-Free Licensed software.

If this is not a go problem, then I apologize. If this is a go problem, please continue reading.

I don't know how to program. But, the best I can guess out of this is that this newer version doesn't like my version of go that I have installed, but version 0.84 from about two to three weeks ago did. I am guessing this for two reasons. First, it mentions go in the error lines several times. Second, I'm pretty sure go was the reason that it failed to run for me many, many months ago as well.

If this is a go issue, why is go so persistently problematic for this project? Why not simply pic a version of go that's pretty far down on the version chart and simply stick with it as long as possible unless absolutely necessary to update to a newer version of go for a major feature?

Because it seems to me that the version of go needed to install as a dependency to be able to run this project jumps all over the place depending on every update that comes out, or every month or so.

This is extremely problematic for everyone not using a rolling release GNU + Linux OS or windows because the various updates to go don't seem to play at all well with each other and updating to a newer version of go throws a monkey wrench into everything.

This is even more extremely problematic for using an OS like Trisquel because completely Free Software operating systems are often forks of other operating systems and the time it takes to flush out all the proprietary code from what they are forking from typically means that they are about a version or so behind the project they are forking from. So, while Trisquel 9.0 beta is still being worked on, it's forked from about a cycle or two older version of ubuntu.

This means that the versions of go available to me is about a cycle or two, or more, behind what people running ubuntu have access to. I have no idea how difficult it would be to manually install a more modern version of go and I really just don't feel like finding this out right now.

What is the reason for the go dependency bouncing all over the place? Picking a version that is new enough to do what IKEMEN GO needs it to do, but is otherwise the oldest, would make running this project as easy as possible for the largest amount of people using a GNU + Linux OS. Constantly updating go places the usability of this project in the hands of only the people who use specific distributions that keep up with your personal go update cycle or for people who can brave installing the newest version of go manually.

I check on this project about at least once daily to see if the code updated and to try to run the newest version if it has to try out new features and see what's changed. It's very exciting. But, about every so many weeks the project just fails to launch for me at all and then it comes back again a few weeks later. Unless I'm wrong, it almost always seems tied to go.

And, also, it seems your automated builder is no longer outputting mac files. This doesn't really concern me as I don't run mac. But, mac people would probably like automated versions back.

I hope I don't sound rude. I love this project and all the great work everyone does on it. It would just be nice to have this problem resolved so that the project doesn't go out on me for weeks at a time before a version that I can run happens again.

Maybe it has nothing to do with go. I don't know. But, this happens a lot to me.

**Comment by Windblade-GR01** [comment]
Ikemen GO code is compiled to machine code so the only OS dependencies are OpenAL and OpenGL.
Go is not needed to be installed to run a  compiled exe, at least on Windows and MacOS work this way.

The error seems GLFW related.

I'll create a Trisquel VM and fix it.

**Comment by EVILEDLIBRE** [comment]
Thank you. I wasn't sure where the error was coming from. I play this a lot and I do like to see what the new changes are when updates are made.

**Comment by Orochikyocr** [comment]
Check if you have a folder called "external" in your ikemen Go folder. If not, download the Windows version and copy the folder from there.

**Comment by EVILEDLIBRE** [comment]
Worked after OS re-install. So, not sure what happened but it works fine now.

**Comment by CSAndrew** [comment]
The same is happening to me now as well. I'm on Kubuntu 20.04 at the moment.
