### ISSUE TITLE
Mac versions no longer being made in auto build.

### ISSUE THREAD

**Issue by EVILEDLIBRE** [Windblade-GR01/Ikemen_GO#96]
I don't really care. I don't use mac. But, some people might. It looks like it is trying to build them, but it does not export the files to the artifacts tab. About a week ago it was leaving out the "Linux" build as well. But, that "Linux" build is back now.

**Comment by Windblade-GR01** [comment]
That was leaving out linux because I did have to adapt the automated build to get them working again. Same with macOS.

I'm searching to fix MacOS builds.
Currently hey do not compile on the Docker image and throw a error on build.
